"""pyvet aggregate — merge audits from multiple sources into a single file."""

from __future__ import annotations

from pathlib import Path

import httpx
import tomlkit
from tomlkit import TOMLDocument

from pyvet.utils.ui import console, print_success, print_error, print_info


def run(args: object) -> int:
    sources_file: str = getattr(args, "sources", "")
    output_file: str | None = getattr(args, "output_file", None)

    if not sources_file:
        print_error("Path to sources file is required.")
        return 1

    sources_path = Path(sources_file)
    if not sources_path.exists():
        print_error(f"Sources file not found: {sources_path}")
        return 1

    urls = [
        line.strip() for line in sources_path.read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]

    if not urls:
        print_error("No URLs found in sources file.")
        return 1

    print_info(f"Aggregating audits from {len(urls)} source(s)...")

    merged_criteria: dict[str, dict] = {}
    merged_audits: dict[str, list] = {}
    merged_wildcards: dict[str, list] = {}
    merged_trusted: dict[str, list] = {}

    for url in urls:
        try:
            resp = httpx.get(url, follow_redirects=True, timeout=30)
            resp.raise_for_status()
            doc = tomlkit.parse(resp.text)
        except Exception as e:
            print_error(f"Failed to fetch {url}: {e}")
            continue

        # Merge criteria (must be identical across sources)
        for name, defn in doc.get("criteria", {}).items():
            if name in merged_criteria:
                existing_desc = merged_criteria[name].get("description", "")
                new_desc = defn.get("description", "")
                if existing_desc and new_desc and existing_desc != new_desc:
                    print_error(
                        f"Criteria '{name}' has different descriptions across sources."
                    )
                    return 1
            else:
                merged_criteria[name] = dict(defn)

        # Merge audits
        for pkg, entries in doc.get("audits", {}).items():
            if pkg not in merged_audits:
                merged_audits[pkg] = []
            for entry in entries:
                e = dict(entry)
                e["aggregated-from"] = url
                merged_audits[pkg].append(e)

        # Merge wildcard-audits
        for pkg, entries in doc.get("wildcard-audits", {}).items():
            if pkg not in merged_wildcards:
                merged_wildcards[pkg] = []
            for entry in entries:
                e = dict(entry)
                e["aggregated-from"] = url
                merged_wildcards[pkg].append(e)

        # Merge trusted
        for pkg, entries in doc.get("trusted", {}).items():
            if pkg not in merged_trusted:
                merged_trusted[pkg] = []
            for entry in entries:
                e = dict(entry)
                e["aggregated-from"] = url
                merged_trusted[pkg].append(e)

        audit_count = sum(len(v) for v in doc.get("audits", {}).values())
        print_success(f"  {url}: {audit_count} audits")

    # Build output document
    out = tomlkit.document()
    out.add(tomlkit.comment("Aggregated audits — auto-generated by pyvet aggregate"))
    out.add(tomlkit.nl())

    if merged_criteria:
        criteria_table = tomlkit.table()
        for name in sorted(merged_criteria):
            ct = tomlkit.table()
            for k, v in merged_criteria[name].items():
                ct[k] = v
            criteria_table[name] = ct
        out["criteria"] = criteria_table

    if merged_wildcards:
        wc_table = tomlkit.table()
        for pkg in sorted(merged_wildcards):
            aot = tomlkit.aot()
            for entry in merged_wildcards[pkg]:
                t = tomlkit.table()
                for k, v in entry.items():
                    t[k] = v
                aot.append(t)
            wc_table[pkg] = aot
        out["wildcard-audits"] = wc_table

    if merged_audits:
        audits_table = tomlkit.table()
        for pkg in sorted(merged_audits):
            aot = tomlkit.aot()
            for entry in merged_audits[pkg]:
                t = tomlkit.table()
                for k, v in entry.items():
                    t[k] = v
                aot.append(t)
            audits_table[pkg] = aot
        out["audits"] = audits_table

    if merged_trusted:
        trusted_table = tomlkit.table()
        for pkg in sorted(merged_trusted):
            aot = tomlkit.aot()
            for entry in merged_trusted[pkg]:
                t = tomlkit.table()
                for k, v in entry.items():
                    t[k] = v
                aot.append(t)
            trusted_table[pkg] = aot
        out["trusted"] = trusted_table

    output = tomlkit.dumps(out)

    if output_file:
        Path(output_file).write_text(output, encoding="utf-8")
        print_success(f"Aggregated audits written to {output_file}")
    else:
        console.print(output)

    total_audits = sum(len(v) for v in merged_audits.values())
    print_info(f"Total: {total_audits} audit entries from {len(urls)} sources")
    return 0
